# Generated by Django 3.2.5 on 2022-05-03 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendationSystem', '0002_artists_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='artists',
            name='description',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('director', models.CharField(max_length=255)),
                ('release_date', models.CharField(max_length=255)),
                ('poster', models.CharField(max_length=255)),
                ('overview', models.CharField(max_length=255)),
                ('cast', models.ManyToManyField(related_name='cast', to='recommendationSystem.artists')),
                ('genres', models.ManyToManyField(related_name='genres', to='recommendationSystem.genres')),
            ],
        ),
    ]
