# Generated by Django 3.2.5 on 2022-05-03 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendationSystem', '0003_auto_20220503_1729'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='movies',
            table='movies',
        ),
    ]
