# Generated by Django 3.2.5 on 2022-05-05 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendationSystem', '0005_alter_movies_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='cast',
            field=models.ManyToManyField(related_name='cast', to='recommendationSystem.Artists'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='genres',
            field=models.ManyToManyField(related_name='genres', to='recommendationSystem.Genres'),
        ),
    ]
