# Generated by Django 3.2.5 on 2022-11-28 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommendationSystem', '0007_auto_20220505_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='cast',
            field=models.ManyToManyField(related_name='cast', to='recommendationSystem.Artists'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='genres',
            field=models.ManyToManyField(related_name='genres', to='recommendationSystem.Genres'),
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendationSystem.movies')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendationSystem.visitors')),
            ],
            options={
                'db_table': 'watchlist',
            },
        ),
    ]
